export const OFFSET_ROTATION_ANGLE = 95;

export const OFFSET_ARM_PITCH_ANGLE = 50;

export const WEBSOCKET_SERVER_URL = "http://localhost:9999";

export const WEBSOCKET_RESPONSE_CODE_MAP = {
    TASK_CURRENT_STATUS: 0,
    SUCCESS_GET_POINTLIFT_TASK: 1,
    CURRENT_MOVING_POSTURE: 20,
    CURRENT_MOVING_ANGLE: 201,
    CURRENT_MOVING_DISTANCE: 202,
    CURRENT_MOVING_HOOK_HEIGHT: 203,

    CURRENT_OTHER_WORK_PARAMS: 22,
    CURRENT_OTHER_WORK_PARAMS_FIRST: 221,
    CURRENT_OTHER_WORK_PARAMS_SECOND: 222,
    CURRENT_OTHER_WORK_PARAMS_THIRD: 223,


    CURRENT_LIFTING_HOOK_PARAMS: 23,
    CURRENT_LIFTING_HOOK_PARAMS_FIRST: 231,
    CURRENT_LIFTING_HOOK_PARAMS_SECOND: 232,
    CURRENT_LIFTING_HOOK_PARAMS_THIRD: 233,

    AUTO_TRANSPORT_END: 2,

    EMERGENCY_STOP: 99,

    SYSTEM_INFO: 100,

}

export const SYSTEM_INFO_TYPE_MAP = {
    idle: 0,
    pointLift: 1,
}